version: "3.5"

services:
  back-viavep:
   container_name: back-viavep
   build: .
   ports:
    - "8000:8000"
   restart: always
   depends_on:
    - db
   volumes:
    - .:/app/back-viavep
    - vendor-back-viavep:/app/back-viavep/vendor
   networks:
    - laravel

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streamer
      MYSQL_USER: streamer
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
   name: laravel
   driver: bridge

volumes:
  vendor-back-viavep:
    name: vendor-back-viavep
  dbdata:
    driver: local